# Fastfile

platform :ios do
  desc "Build and upload the iOS app to App Store Connect"
  lane :upload_to_app_store do
    # Match the provisioning profiles and certificates using match
    match(type: "appstore")

    # Build the iOS app
    gym(
      scheme: "com.companyname.youkoso",
      export_method: "app-store"
    )

    # Upload the binary to App Store Connect using deliver
    deliver(
      username: ENV["APPLE_ID"],
      app_identifier: "com.companyname.youkoso",
      ipa: "./bin/publish/youkoso.dll"
    )

    # Upload the binary to App Store Connect using pilot
    pilot
  end
end