name: build and publish iOS app
on:
  push:
    branches:
      - master
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0
      - uses: actions/setup-xcode@v2
        with:
          apple-id: ${{ secrets.APPLE_ID }}
          app-id-ios: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
      - run: dotnet build -c Release -t iOS
      - run: dotnet publish -c Release -t iOS -r iOS
