name: Build iOS App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x

    - name: Install Maui iOS
      run: dotnet workload install maui-ios

    - name: Install maccatalyst
      run: dotnet workload install maccatalyst

    - name: Restore Dependencies
      run: dotnet restore youkoso.sln

    - name: Sign and Export IPA
      run: |
        # 証明書ファイル、プロビジョニングファイルのパスをプロジェクトフォルダ「youkoso」に基づいて指定して、それらを使用します
        codesign -s "youkoso/certificate.p12" --entitlements "youkoso/Path/to/YourApp.entitlements" "youkoso/Path/to/youkoso.app" --provisioning-profile "youkoso/youkoso.mobileprovision"

    - name: Build iOS App
      run: dotnet build youkoso/youkoso.csproj -f net7.0-ios -c Release 

