name: Build iOS App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x

    - name: Install Maui iOS
      run: dotnet workload install maui-ios

    - name: Install maccatalyst
      run: dotnet workload install maccatalyst

    - name: Restore Dependencies
      run: dotnet restore youkoso.sln

    - name: Install Certificate and Provisioning Profile to Keychain
      run: |
        security create-keychain -p mysecretpassword build.keychain
        security import youkoso/certificate.p12 -k ~/Library/Keychains/build.keychain -P "shadia12" -T /usr/bin/codesign
        security import youkoso/youkoso.mobileprovision -k ~/Library/Keychains/build.keychain -T /usr/bin/codesign
        security list-keychains -s ~/Library/Keychains/build.keychain

    - name: Build iOS App
      run: dotnet build youkoso/youkoso.csproj -f net7.0-ios -c Release 

