name: Build iOS App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x

    - name: Install .NET MAUI
      run: dotnet workload install maui

    - name: Install dependencies
      run: dotnet restore

    - name: Build iOS App
      run: dotnet build -t:Restore,Build -f net7.0 -r ios

    - name: Sign and Export IPA
      run: |
        # 証明書ファイル、プロビジョニングファイルのパスをプロジェクトフォルダ「youkoso」に基づいて指定して、それらを使用します
        codesign -s "youkoso/certificate.p12" --entitlements "youkoso/Path/to/YourApp.entitlements" "youkoso/Path/to/youkoso.app" --provisioning-profile "youkoso/youkoso.mobileprovision"
        # .ipaファイルのエクスポート
        xcodebuild -exportArchive -archivePath "youkoso/Path/to/youkoso.xcarchive" -exportPath "youkoso/Path/to/Output" -exportOptionsPlist "youkoso/Path/to/ExportOptions.plist"
        mv "youkoso/Path/to/Output/youkoso.ipa" "youkoso/Path/to/youkoso.ipa"

    - name: Upload IPA
      uses: actions/upload-artifact@v2
      with:
        name: YourApp
        path: Path/to/YourApp.ipa
