name: iOS Starter Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    name: Build and Test Default Scheme on iPhone Simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Default Scheme
        run: echo "youkoso" > default

      - name: Build and Test
        env:
          scheme: ${{ env.default }}
          platform: iOS Simulator
        run: |
          device=$(xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//")
          if [ $scheme = default ]; then scheme=$(cat default); fi
          xcodebuild build-for-testing -scheme "$scheme" -project "youkoso/youkoso.csproj" -destination "platform=$platform,name=$device"
          xcodebuild test-without-building -scheme "$scheme" -project "youkoso/youkoso.csproj" -destination "platform=$platform,name=$device"
