name: Build and Publish iOS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'

    - name: Install Maui iOS
      run: dotnet workload install maui-ios

    - name: Install maccatalyst
      run: dotnet workload install maccatalyst

    - name: Restore Dependencies
      run: dotnet restore youkoso.sln

    - name: Install .NET MAUI Dependencies
      run: dotnet msbuild /t:Restore youkoso/youkoso.csproj

    - name: Build and Publish iOS App
      run: dotnet publish youkoso/youkoso.csproj --configuration Release
