name: iOS Starter Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    name: Build and Test Default Scheme on iPhone Simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Install .NET MAUI Dependencies
        run: dotnet workload install maui-ios maccatalyst

      - name: Restore Dependencies
        run: dotnet restore youkoso.sln

      - name: Clean Project
        run: dotnet clean youkoso/youkoso.csproj

      - name: Install .NET MAUI Dependencies and Publish iOS App
        run: dotnet msbuild /t:Restore youkoso/youkoso.csproj

      - name: Build Project
        run: dotnet build youkoso/youkoso.csproj --configuration Release --output ./bin '/p:CodesignKey=Apple Development: M6XQ2Z2NSJ'

      - name: Publish iOS App
        run: dotnet publish youkoso/youkoso.csproj --configuration Release --framework net7.0-ios --runtime ios-arm64 --self-contained --output ./bin/publish

      - name: Set Environment Variables
        run: |
          export APP_STORE_CONNECT_KEY_ID=${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          export APP_STORE_CONNECT_ISSUER_ID=${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install Fastlane
        run: sudo gem install fastlane -NV

      - name: Build and Upload
        run: fastlane upload_to_app_store
        env:
          FASTLANE_USERNAME: ${{ secrets.APPLE_ID }}
          FASTLANE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}

      - name: Upload to App Store Connect
        run: fastlane deliver --ipa "./bin/publish/youkoso.dll" --username ${{ secrets.APPLE_ID }} --verbose
