name: iOS Starter Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    name: Build and Test Default Scheme on iPhone Simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'

    - name: Install Maui iOS
      run: dotnet workload install maui-ios

    - name: Install maccatalyst
      run: dotnet workload install maccatalyst

    - name: Restore Dependencies
      run: dotnet restore youkoso.sln

    - name: Set Environment Variables and Publish iOS App
      run: |
        export APP_STORE_CONNECT_KEY_ID="${{ secrets.APP_STORE_CONNECT_KEY_ID }}"
        export APP_STORE_CONNECT_ISSUER_ID="${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}"
        export APP_STORE_CONNECT_KEY="${{ secrets.APP_STORE_CONNECT_KEY }}"

    - name: Install .NET MAUI Dependencies and Publish iOS App
      run: |
        dotnet msbuild /t:Restore youkoso/youkoso.csproj
