name: Build .NET MAUI Android app

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Install Xcode
      uses: actions/setup-xcode@v2
      with:
        xcode-version: 14.3
        repository: https://github.com/actions/setup-xcode

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x

    - name: Install .NET MAUI
      run: dotnet workload install maui

    - name: Restore dependencies
      run: dotnet restore

    - name: Build Application
      run: dotnet build youkoso/youkoso.csproj -f:net7.0-ios -c:Release

    - name: Build AAB and APK
      run: dotnet publish youkoso/youkoso.csproj -f:net7.0-ios -c:Release

    - name: Copy files to bin folder
      run: |
        cp -r youkoso/bin/Release/net7.0-android/publish/* youkoso/bin/  # ビルドされたファイルをコピー

    - name: Publish files as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: youkoso/bin/  # アーティファクトとしてアップロードするフォルダのパス
