name: Build .NET MAUI iOS App

on:
  push:
    branches:
      - master

jobs:
  build-and-publish-ios:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Install .NET MAUI Dependencies
      run: dotnet workload install maui-ios maccatalyst

    - name: Restore NuGet Packages
      run: dotnet restore youkoso.sln

    - name: Build .NET MAUI iOS App
      run: dotnet build youkoso.sln --configuration Release --no-restore

    - name: Create Keychain and Unlock
      run: fastlane create_keychain name:MyKeychain password:MyPassword
      env:
        MY_KEYCHAIN_PATH: $HOME/Library/Keychains/MyKeychain-db
        KEYCHAIN_PASSWORD: MyPassword # キーチェーンのパスワードを設定
        KEYCHAIN_PASSWORD2: "shadia12" # キーチェーンのパスワードを設定

    - name: Import Certificate and Provisioning Profile
      run: |
        # 証明書ファイルをキーチェーンにエクスポート
        security import youkoso/certificate.p12 -k $MY_KEYCHAIN_PATH -P $KEYCHAIN_PASSWORD2 -T /usr/bin/codesign

        # プロビジョニングファイルをキーチェーンにエクスポート
        security import youkoso/youkoso.mobileprovision -k $MY_KEYCHAIN_PATH -T /usr/bin/codesign

        # 証明書のパスワードを指定
        security set-keychain-password -p $KEYCHAIN_PASSWORD $MY_KEYCHAIN_PATH

    - name: Build iOS App
      run: |
        msbuild youkoso.sln /t:Clean,Build /p:Configuration=Release /p:Platform=iPhoneSimulator

    - name: Archive iOS App
      run: |
        msbuild youkoso.sln /t:Archive /p:Configuration=Release /p:Platform=iPhone

    - name: Clean Up Keychain
      run: fastlane delete_keychain name:MyKeychain
