name: Build and Publish iOS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'

    - name: Install Maui iOS
      run: dotnet tool install -g maui-ios --source https://pkgs.dev.azure.com/dotnet/ maui

    - name: Restore Dependencies
      run: dotnet restore youkoso.sln

    - name: Build and Publish iOS App
      run: dotnet publish youkoso/youkoso.csproj --configuration Release --output publish
