name: iOS Starter Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    name: Build and Test Default Scheme on iPhone Simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2  # Update to latest version
        with:
          dotnet-version: '7.0.x'

      - name: Install .NET MAUI Dependencies
        run: dotnet workload install maui-ios maccatalyst

      - name: Restore Dependencies
        run: dotnet restore youkoso.sln

      - name: Clean Project
        run: dotnet clean youkoso/youkoso.csproj

      - name: Install .NET MAUI Dependencies and Publish iOS App
        run: dotnet msbuild /t:Restore youkoso/youkoso.csproj

      - name: Build Project
        run: dotnet build youkoso/youkoso.csproj --configuration Release --output ./bin

      - name: Publish iOS App
        run: dotnet publish youkoso/youkoso.csproj --configuration Release --output ./bin/publish

      - name: Set Environment Variables
        run: |
          echo "APP_STORE_CONNECT_KEY_ID=${{ secrets.APP_STORE_CONNECT_KEY_ID }}" >> $GITHUB_ENV
          echo "APP_STORE_CONNECT_ISSUER_ID=${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}" >> $GITHUB_ENV
          echo "APP_STORE_CONNECT_KEY=${{ secrets.APP_STORE_CONNECT_KEY }}" >> $GITHUB_ENV

      - name: Install Transporter
        run: sudo gem install fastlane

      - name: Upload to App Store Connect
        run: fastlane deliver --ipa "./bin/publish/youkoso.dll" --username ${{ secrets.APP_STORE_CONNECT_USERNAME }} --verbose
