name: Build .NET MAUI iOS App

on:
  push:
    branches:
      - master

jobs:
  build-and-publish-ios:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Install .NET MAUI Dependencies
      run: dotnet workload install maui-ios maccatalyst

    - name: Restore NuGet Packages
      run: dotnet restore youkoso.sln

    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Install Fastlane
      run: gem install fastlane

    - name: Create Keychain and Unlock
      run: fastlane create_keychain_ios

    - name: Set Fastlane to interactive mode
      run: export FASTLANE_OPT_OUT_USAGE=false

    - name: Import Certificate and Provisioning Profile
      run: |
        # キーチェーンにアクセス
        security default-keychain -s app-signing
        security unlock-keychain -p MyPassword app-signing

    - name: Import Certificate and Provisioning Profile
      run: |
        # 証明書ファイルをキーチェーンにエクスポート
        security import youkoso/certificate.p12 -P Youkoso1234 -A -t cert -f pkcs12 -k app-signing

        # プロビジョニングファイルをキーチェーンにエクスポート
        security import youkoso/youkoso.mobileprovision -k app-signing -t cert

    - name: Install Certificate and Provisioning Profile
      run: |
        # 証明書とプロビジョニングファイルをインストール
        security unlock-keychain -p MyPassword app-signing
        security set-keychain-settings -l - u -t 3600 app-signing
        security import youkoso/certificate.p12 -P Youkoso1234 -A -t cert -f pkcs12 -k app-signing
        security import youkoso/youkoso.mobileprovision -k app-signing -t cert

    - name: Build iOS App
      run: dotnet build youkoso.sln --configuration Release --no-restore /p:TargetFramework=net7.0-ios

    - name: Archive iOS App
      run: dotnet publish youkoso.sln -f net7.0-ios -c Release

    - name: Copy files to bin folder
      shell: powershell
      run: |
        Copy-Item -Path .\youkoso\bin\Release\net7.0-ios\* -Destination .\youkoso\bin\ -Recurse  # ビルドされたファイルをコピー

    - name: Publish files as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: youkoso\bin\  # アーティファクトとしてアップロードするフォルダのパス

    #- name: Clean Up Keychain
      #run: fastlane delete_keychain name:MyKeychain
