name: Build .NET MAUI iOS App

on:
  push:
    branches:
      - master

jobs:
  build-and-publish-ios:
    runs-on: macos-latest

    env:
      p12_password: ${{ secrets.p12_password }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Install .NET MAUI Dependencies
      run: dotnet workload install maui-ios maccatalyst

    - name: Restore NuGet Packages
      run: dotnet restore youkoso.sln

    - name: Install the Apple certificate and provisioning profile
      env:
        BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
        P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
        BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      run: |
        # create variables
        CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
        PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
        KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

        # import certificate and provisioning profile from secrets
        echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
        echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH

        # create temporary keychain
        security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
        security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

        # import certificate to keychain
        security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
        security list-keychain -d user -s $KEYCHAIN_PATH

        # apply provisioning profile
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

    - name: Build iOS App
      run: dotnet build Youkoso.sln --configuration Release -f net7.0-ios

    - name: Archive iOS App
      run: dotnet publish youkoso.sln -f net7.0-ios -c Release

    - name: Copy files to bin folder
      shell: powershell
      run: |
        Copy-Item -Path .\youkoso\bin\Release\net7.0-ios\* -Destination .\youkoso\bin\ -Recurse  # ビルドされたファイルをコピー

    - name: Publish files as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: youkoso\bin\  # アーティファクトとしてアップロードするフォルダのパス

